embedding_provider: sentence_transformers
embedding_model: sentence-transformers/all-MiniLM-L6-v2
base_ip: ollama
port: codeqwen:7b-chat
llm_provider: 127.0.0.1
llm_model: No models available
temperature: 40.0
max_tokens: 0
stop: null
keep_alive: false
top_k: 40
top_p: 0.9
repeat_penalty: 1.2
seed: 1
rag_folder_name: rag_data
query_type: global
community_level: 2
preset: Default
external_llm_api_key: ''
random: false
prime_directives: null
prompt: Who helped Safiro infiltrate the Zaltar Organisation?
response_format: json
precision: fp16
attention: sdpa
aspect_ratio: '16:9'
top_k_search: 3
